-- Milestone 5: DML Operations & Validation Queries

-- ============================================================================
-- 1. DML OPERATIONS (UPDATE and DELETE).
-- ============================================================================

-- UPDATE OPERATION: Increase the LaborCost for jobs that are currently 'Pending' 
-- by 10% because of a newly introduced workshop policy change.
UPDATE SERVICE_JOB
SET LaborCost = LaborCost * 1.10
WHERE Status = 'Pending';

-- DELETE OPERATION: Delete an invoice that was generated by mistake (e.g., 
-- marked as 'Unpaid' with no valid PaymentMethod).
DELETE FROM INVOICE
WHERE PaymentStatus = 'Unpaid' AND PaymentMethod = 'N/A' AND InvoiceID = 3;


-- ============================================================================
-- 2. VALIDATION QUERIES.
-- ============================================================================

-- A. COUNT(*) for each table to confirm row counts
SELECT 'CUSTOMER' AS TableName, COUNT(*) AS RowCount FROM CUSTOMER
UNION ALL
SELECT 'VEHICLE', COUNT(*) FROM VEHICLE
UNION ALL
SELECT 'MECHANIC', COUNT(*) FROM MECHANIC
UNION ALL
SELECT 'SERVICE_JOB', COUNT(*) FROM SERVICE_JOB
UNION ALL
SELECT 'SPARE_PART', COUNT(*) FROM SPARE_PART
UNION ALL
SELECT 'SERVICE_PARTS', COUNT(*) FROM SERVICE_PARTS
UNION ALL
SELECT 'INVOICE', COUNT(*) FROM INVOICE;

/*
EXPECTED OUTPUT:
TableName       RowCount
CUSTOMER        50
VEHICLE         50
MECHANIC        50
SERVICE_JOB     50
SPARE_PART      50
SERVICE_PARTS   65
INVOICE         49   (Because we successfully deleted InvoiceID = 3 above)
*/

-- B. NULL check on key columns
-- Checking if any Customer is missing a required first name or phone number.
SELECT CustomerID, FirstName, Phone
FROM CUSTOMER
WHERE FirstName IS NULL OR Phone IS NULL;

/*
EXPECTED OUTPUT:
Empty set (0 rows) - Confirms our NOT NULL constraint and valid INSERT data.
*/

-- C. JOIN-based check to confirm foreign key integrity
-- Query to ensure that every Service Job is linked to a valid Vehicle and a valid Customer.
-- By using a LEFT JOIN and checking for NULLs on the right side, we can find orphans.
SELECT 
    j.JobID, 
    j.Date, 
    v.RegNo, 
    c.FirstName, 
    c.LastName
FROM 
    SERVICE_JOB j
LEFT JOIN 
    VEHICLE v ON j.VehicleID = v.VehicleID
LEFT JOIN 
    CUSTOMER c ON v.CustomerID = c.CustomerID
WHERE 
    v.VehicleID IS NULL OR c.CustomerID IS NULL;

/*
EXPECTED OUTPUT:
Empty set (0 rows) - Confirms that there are no orphaned SERVICE_JOB records. 
Every job successfully joins back to a vehicle and its owning customer.
*/
